FROM openjdk:17

WORKDIR /app

ARG JAR_FILE

COPY target/${JAR_FILE} /app/api.jar
COPY wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh

EXPOSE 8080

CMD ["./wait-for-it.sh", "rabbitmq:5672", "--", "java", "-jar", "api.jar"]
